project:
  type: website

website:
  title: "CU DataSoc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: about/team.qmd
            text: Team
      - href: blog.qmd
        text: Blog
    right:
      - text: "Become a Member"
        icon: person-plus
        href: https://docs.google.com/forms/d/e/1FAIpQLSeh4zYoC1o6MtLc3_0RbsqXRE1UbtmK5XqcWGJOi5BboURciA/viewform 
      - text: "Discord"
        href: https://discord.gg/4RKwHYSCpN
      


format:
  html:
    theme:
      - minty
    theme-vars:
      primary: "#467946"
      secondary: "#467946"
      success: "#467946"
      info: "#3d3d3f"
      warning: "#c9a94a"
      danger: "#a94442"
      light: "#f8f9fa"
      dark: "#212529"
      link-color: "#467946"
    css: styles.css
    toc: true




